language: java

addons:
  sauce_connect:
    username: JaimePerezP
    access_key: ac5fb3c9-f21a-4952-b319-a11d1d3b7f91
  
script:
  - mvn verify

deploy:
  provider: heroku
  api_key:
    secure: 5468840c-379e-49a7-b61d-274f5f9f15ff
  app: the-good-health
