language: java

sudo: required
dist: xenial

services:
  - xvfb

addons: # get google-chrome-stable
  chrome: stable

install:
  - wget -N http://chromedriver.storage.googleapis.com/77.0.3865.40/chromedriver_linux64.zip -P ~/
  - unzip ~/chromedriver_linux64.zip -d ~/
  - rm ~/chromedriver_linux64.zip
  - sudo mv -f ~/chromedriver /usr/local/share/
  - sudo chmod +x /usr/local/share/chromedriver

before_script:
  - "export DISPLAY=:99.0"
  - sleep 3 # give xvfb some time to start
  - rackup  # start a Web server
  - sleep 3 # give Web server some time to bind to sockets, etc
  
script:
  - mvn test

deploy:
  provider: heroku
  api_key:
    secure: 5468840c-379e-49a7-b61d-274f5f9f15ff
  app: the-good-health
