language: java

addons: # get google-chrome-stable
  chrome: stable

install:
  - wget -N http://chromedriver.storage.googleapis.com/77.0.3865.10/chromedriver_linux64.zip -P ~/
  - unzip ~/chromedriver_linux64.zip -d ~/
  - rm ~/chromedriver_linux64.zip
  - sudo mv -f ~/chromedriver /usr/local/share/
  - sudo chmod +x /usr/local/share/chromedriver
  
script:
  - mvn test

deploy:
  provider: heroku
  api_key:
    secure: 5468840c-379e-49a7-b61d-274f5f9f15ff
  app: the-good-health
