language: java

before_script:
   - sudo apt-get install ant-optional

script:
- cd TheGoodHealth
- ant build
- ant CucumberRunner
- cd ..

deploy:
  provider: heroku
  api_key:
    secure: 5468840c-379e-49a7-b61d-274f5f9f15ff
  app: tgh.jar
  on:
   repo: JaimePerezP/Proyecto4-ISO-2019_E4
